version: 4.2.0
files:
  - url: POS System Setup 4.2.0.exe
    sha512: ldh9igdj5YPCWc/iOwuBu8CkJzDugQveWzbZ/8dFRt5o/M3Q6VFKmvQf0dWzwHtHIslnuZC9/b+V34xLzaQdYQ==
    size: 98642921
path: POS System Setup 4.2.0.exe
sha512: ldh9igdj5YPCWc/iOwuBu8CkJzDugQveWzbZ/8dFRt5o/M3Q6VFKmvQf0dWzwHtHIslnuZC9/b+V34xLzaQdYQ==
releaseDate: '2025-08-10T12:09:32.308Z'
